### ISSUE TITLE
均質化の部分について

### ISSUE THREAD

**Issue by dwatanabee** [PANFACTORY/PANSFEM2#2]
お久しぶりです．名大の博士課程の渡邉です．
均質化の部分の実装で参考にしたコード・本などが御座いましたら教えていただきたいです．
というのも，物体力？を計算して解く流れが，自分が知っているアルゴリズムと違うためです．
もちろん，コード自体は合っていると思います！
お手数おかけしますが，宜しくおねがいします．

**Comment by PANFACTORY** [comment]
@dwatanabee 
お久しぶりです。
PANSFEM2をご覧頂きありがとうございます。
均質化法の実装に関しては寺田賢次郎先生が執筆された「均質化法入門 (計算力学レクチャーシリーズ)」の4章に基づいているはずです。
ただ、コーディングのミスも十分に考えられますので、もし誤りを発見された場合は大変お手数ですがご一報いただけないでしょうか。
以上宜しくお願い致します。

**Comment by dwatanabee** [comment]
「均質化法入門」を読みました．
こちらの流れの方が一般的みたいですね．
研究室のコードでは，各方向に強制変位を与えるような方法で実装されていたため混乱してました．
教えていただきありがとうございます．
